{application,testmochi,
             [{description,"testmochi"},
              {vsn,"0.1"},
              {modules,[testmochi,testmochi_app,testmochi_deps,testmochi_sup,
                        testmochi_web]},
              {registered,[]},
              {mod,{testmochi_app,[]}},
              {env,[]},
              {applications,[kernel,stdlib,crypto]}]}.
